apiVersion: apps/v1
kind: Deployment
metadata:
  name: julioferreira-handler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: julioferreira-handler
  template:
    metadata:
      labels:
        app: julioferreira-handler
    spec:
      containers:
      - name: julioferreira-handler
        image: julioferreira20/julioferreira-handler:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/app/usermodule.py"
          subPath: "pyfile"
        env:
        - name: REDIS_HOST
          value: "192.168.121.189"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile